name: dart2
version: 0.1.0
homepage: https://www.sandromaglione.com/
# repository: https://github.com/SandroMaglione/fpdart
# description: Functional programming in Dart and Flutter. All the main functional programming types and patterns fully documented, tested, and with examples.
# author: Maglione Sandro <lass.maglio@gmail.com>
# documentation: https://www.sandromaglione.com/course/fpdart-functional-programming-dart-and-flutter

environment:
  sdk: ">=2.13.0 <4.0.0"

dev_dependencies:
  lints: ^2.0.1
  test: ^1.24.1
